module TestConstants
  RESOURCES_ILLEGAL_MARC_IN_JSON_JSON = "illegal-marc-in-json.json"
  RESOURCES_MARC_IN_JSON_JSON = "marc-in-json.json"
  RESOURCES_MARC_JSON_JSON = "marc-json.json"
  RESOURCES_LEGAL_JSON_MARC_IN_JSON_JSON = "legal-json-marc-in-json.json"
  RESOURCES_BAD_LEADERS_10_11_MRC = "bad_leaders_10_11.mrc"
  RESOURCES_BAD_TOO_LONG_PLUS_2_MRC = "bad_too_long_plus_2.mrc"
  RESOURCES_SUMMERLAND_MRC = "summerland.mrc"
  RESOURCES_SUMMERLAND_XML = "summerland.xml"
  RESOURCES_SUMMERLAND_MARC_IN_JSON_JSON = "summerland-marc-in-json.json"
  RESOURCES_SUMMERLAND_MARC_IN_JSON_INDENTED_JSON = "summerland-marc-in-json-indented.json"
  RESOURCES_SUMMERLAND_MARC_JSON_JSON = "summerland-marc-json.json"
  RESOURCES_SUMMERLAND_INDENTED_MARC_JSON_JSON = "summerland-indented-marc-json.json"
  RESOURCES_BRKRTEST_MRC = "brkrtest.mrc"
  RESOURCES_CHABON_MRC = "chabon.mrc"
  RESOURCES_CHABON_XML = "chabon.xml"
  RESOURCES_OCLC814388508_XML = "OCLC_814388508.xml"
  RESOURCES_CYRILLIC_CAPITAL_E_MRC = "cyrillic_capital_e.mrc"
  RESOURCES_GREEK_MISSING_CHARSET_MRC = "greekmissingcharsetchange.mrc"
  RESOURCES_CHINESE_MANGLED_MULTIBYTE_MRC = "chinese_mangled_multibyte.mrc"
  RESOURCES_BAD_NUMERIC_CHARACTER_REFERENCE_MRC = "loongboonmee.mrc"
end